export { createTrafficStore, normalizePath, shouldIgnore, recordRequest, getTrafficSnapshot } from './recorder';
export { filterEntries, groupByMethod, sortByFrequency } from './filter';
export { deduplicateEntries, pickLatestPerKey, entryKey } from './deduplicator';
export { sampleEntries, shouldSample, applyMaxPerRoute } from './sampler';
export { aggregateEntries, topRoutes, routesSince } from './aggregator';
export { sortEntriesByTime, sliceReplayWindow } from './replay';
export { serializeEntries, deserializeEntries, serializeToCSV } from './exporter';
export { classifyEntry, classifyEntries } from './classifier';
export { computeRouteStats, computeTrafficStats } from './stats';
export { transformEntry, transformEntries } from './transformer';
export { matchEntry, filterByPattern, groupByPattern } from './matcher';
export { scoreRoute, scoreRoutes } from './scorer';
export { paginateEntries, paginateByRoute, getPage } from './paginator';
export { cursorPaginate, encodeCursor, decodeCursor } from './cursor';
export { createThrottleStore, shouldThrottle } from './throttler';
export { diffEntries, diffRoutes, hasDrift } from './diff';
export type { TrafficEntry, TrafficStore } from './types';
export type { TrafficDiff, RouteDiff } from './diff';
